# This is a basic workflow to help you get started with Actions

name: My CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  first-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: ['dotnet', 'java', 'failing']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: Building stack for ${{ matrix.stack }}
        run: echo Hello, world!  ${{ matrix.stack }}
      - name: Never Fail if ${{ matrix.stack }} == 'failing'
        if: ${{ matrix.stack == 'failinggggg' }} 
        run: exit 1
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Nothing really
        run: echo Done
  third-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12]
        different-option: [one, two]
  forth-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [1]
    steps:
      - name: Nothing really
        run: echo Done
